# Generated by Django 4.1.7 on 2023-03-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('acronym', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='')),
                ('uni_type', models.CharField(max_length=256)),
                ('overview', models.TextField(max_length=2000)),
                ('establishedـyear', models.IntegerField()),
                ('students_num', models.IntegerField()),
                ('link', models.CharField(max_length=1000)),
                ('apply_rate', models.CharField(max_length=32)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apply.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apply.country'),
        ),
    ]
