# Generated by Django 4.1.7 on 2023-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_alter_city_country_alter_university_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(storage='images', upload_to=''),
        ),
    ]
