# Generated by Django 4.1.7 on 2023-03-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_alter_university_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(upload_to='logos/<django.db.models.fields.CharField>'),
        ),
    ]
